# https://github.com/github/super-linter
name: Super-Linter

#############################
# Start the job on all push #
#############################
on:
  push:
    # branches-ignore: [master]
    # Remove the line above to run when pushing to master
  pull_request:
#    branches: [master]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Super-Linter
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          PYTHON_ISORT_CONFIG_FILE: /github/workspace/superlinter.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
